export const REQUEST_BUSINESSLIST='REQUEST_BUSINESSLIST'
export const GET_BUSINESSLIST_FAILURE='GET_BUSINESSLIST_FAILURE'
export const GET_BUSINESSLIST_SUCCESS='GET_BUSINESSLIST_SUCCESS'

export const REQUEST_RANDOM='REQUEST_RANDOM'
export const GET_RANDOM_SUCCESS='GET_RANDOM_SUCCES'
export const GET_RANDOM_FAILURE='GET_RANDOM_FAILURE'